apiVersion: v1
kind: Template
metadata:
  name: fh-sync-server
  annotations:
    openshift.io/display-name: FeedHenry Sync (Persistent)
    description: FeedHenry Sync Server
    iconClass: icon-nodejs
    tags: instant-app,sync,mobile-service
    template.openshift.io/long-description: Data Synchronisation by FeedHenry.
    template.openshift.io/provider-display-name: FeedHenry
    template.openshift.io/documentation-url: https://github.com/feedhenry/fh-sync-server
    template.openshift.io/support-url: https://github.com/feedhenry/fh-sync-server/issues
labels:
  template: fh-sync-server
parameters:
  - name: MONGODB_ADMIN_PASSWORD
    description: Password for the MongoDB admin user. This value will be generated if not specified.
    generate: expression
    from: "[a-zA-Z0-9]{40}"
  - name: MONGODB_USER_NAME
    description: Username for the created MongoDB user.
    value: "sync-user"
  - name: MONGODB_USER_PASSWORD
    description: Password for the created MongoDB user. This value will be generated if not specified.
    generate: expression
    from: "[a-zA-Z0-9]{40}"
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: fh-sync-server
    annotations:
      mcp/prometheus: "enabled"
    labels:
      app: fh-sync-server
      template: fh-sync-server
  spec:
    ports:
    - name: fh-sync-server
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      run: fh-sync-server
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      template.openshift.io/expose-name: "fh-sync-server"
      template.openshift.io/expose-type: "fh-sync-server"
    labels:
      app: fh-sync-server
      template: fh-sync-server
    name: mongodb
  spec:
    ports:
    - name: mongo
      port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      name: mongodb
    sessionAffinity: None
    type: ClusterIP

- apiVersion: v1
  kind: Service
  metadata:
    name: redis
    labels:
      app: fh-sync-server
      template: fh-sync-server
  spec:
    ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      run: redis
    sessionAffinity: None
    type: ClusterIP

- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: fh-sync-server
      template: fh-sync-server
    name: fh-sync-server
  spec:
    replicas: 1
    selector:
      matchLabels:
        run: fh-sync-server
    strategy:
      activeDeadlineSeconds: 21600
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: RollingUpdate
    template:
      metadata:
        labels:
          run: fh-sync-server
      spec:
        containers:
        - name: fh-sync-server
          env:
          - name: MONGODB_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: mongodb
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: mongodb
          image: feedhenry/fh-sync-server
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
            protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange

- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: fh-sync-server
      template: fh-sync-server
    name: mongodb
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: mongodb
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      type: Recreate
    template:
      metadata:
        labels:
          name: mongodb
      spec:
        containers:
        - name: mongodb
          env:
          - name: MONGODB_USER
            valueFrom:
              secretKeyRef:
                key: database-user
                name: mongodb
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-password
                name: mongodb
          - name: MONGODB_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                key: database-admin-password
                name: mongodb
          - name: MONGODB_DATABASE
            value: sync
          image: centos/mongodb-32-centos7@sha256:aa37993c3be2d4731db79c0c7aba11db3e9352b1adc586c7e9054f57808789c0
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 27017
            timeoutSeconds: 1
          ports:
          - containerPort: 27017
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - mongo 127.0.0.1:27017/$MONGODB_DATABASE -u $MONGODB_USER -p $MONGODB_PASSWORD
                --eval="quit()"
            failureThreshold: 3
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              memory: 512Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/mongodb/data
            name: mongodb-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - mongodb
        from:
          kind: ImageStreamTag
          name: mongodb:3.2
          namespace: openshift
      type: ImageChange
    - type: ConfigChange

- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: fh-sync-server
      template: fh-sync-server
      run: redis
    name: redis
  spec:
    replicas: 1
    selector:
      matchLabels:
        run: redis
    strategy:
      activeDeadlineSeconds: 21600
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: RollingUpdate
    template:
      metadata:
        labels:
          run: redis
      spec:
        containers:
        - name: redis
          image: rhmap/redis:2.18.22
          imagePullPolicy: Always
          ports:
          - containerPort: 6379
            protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange

- apiVersion: v1
  kind: Route
  metadata:
    annotations:
      template.openshift.io/expose-uri: "https://{.spec.host}{.spec.path}"
    name: fh-sync-server
    labels:
      app: fh-sync-server
      template: fh-sync-server
  spec:
    port:
      targetPort: fh-sync-server
    tls:
      termination: edge
    to:
      kind: Service
      name: fh-sync-server
    wildcardPolicy: None

- apiVersion: v1
  kind: Secret
  stringData:
    database-admin-password: ${MONGODB_ADMIN_PASSWORD}
    database-password: ${MONGODB_USER_PASSWORD}
    database-user: ${MONGODB_USER_NAME}
  metadata:
    labels:
      app: fh-sync-server
      template: fh-sync-server
    name: mongodb
  type: Opaque
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: mongodb
    labels:
      app: fh-sync-server
      template: fh-sync-server
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
